import { expect, test } from 'claude-code/testing'

import { addedLines, byLanguage, hasOtherAuthor, identityOf, judge, MAX_ADDED_LINES, parseCommitInfo, parseRecent } from '../hooks/authorship'
import { FORGET } from '../hooks/forget'
import {
  assessmentRequest,
  decideLevel,
  emptyRecord,
  levelPhrase,
  parseAssessment,
  parseRecord,
  progressText,
  recordText,
  skillStates,
  withAssessment,
} from '../hooks/progress'
import type { Assessment } from '../hooks/progress'
import type { Level, Observation, ProgressRecord } from '../types'
import { COMPOSE, DATA_HOME, PANE, SESSION, sessionTest, stubSession, typed } from './kit'

const MEAN = 'def mean(xs):\n    return sum(xs) / len(xs)\n'

function seen(commit: string, skill: string, verdict: 'shown' | 'missed', level: Level, weight = 1): Observation {
  return { commit, project: 'stats', at: 1, skill, verdict, level, weight, note: `${skill} in ${commit}` }
}

function record(observations: Observation[], level: Level | null = null, extra: Partial<ProgressRecord> = {}): ProgressRecord {
  return { ...emptyRecord('python'), observations, level, ...extra }
}

const SAW: Assessment = {
  observations: [
    { commit: '', skill: 'edge-cases', verdict: 'missed', level: 'junior', note: 'stats.py: nothing for an empty list.' },
    { commit: '', skill: 'naming', verdict: 'shown', level: 'junior', note: 'stats.py: clear names.' },
  ],
  level: 'junior',
  why: 'Small, working functions with clear names.',
  next: 'Handle the empty input on purpose, and test it.',
  working: ['edge cases'],
  encouragement: 'Your functions read cleanly.',
}

test('a commit is yours only when your email wrote it, alone, and by hand', async () => {
  const info = parseCommitInfo('abc1234def\0p1\0Me@Example.com\0Me\0Add mean\n\nBody.\n')
  expect(info).toEqual({ hash: 'abc1234def', parents: ['p1'], email: 'me@example.com', name: 'Me', message: 'Add mean\n\nBody.' })
  expect(parseCommitInfo('not a commit')).toBe(null)
  expect(identityOf('me@example.com\n', ' ME@example.com', '', 'not-an-email')).toEqual(['me@example.com'])
  expect(parseRecent('aaaaaaa\0me@example.com\nbbbbbbb\0guido@python.org\n')).toEqual([
    { hash: 'aaaaaaa', email: 'me@example.com' },
    { hash: 'bbbbbbb', email: 'guido@python.org' },
  ])

  expect(hasOtherAuthor('Add mean\n\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>')).toBe(true)
  expect(hasOtherAuthor('Add mean\n\nco-authored-by: Ada <ada@example.com>')).toBe(true)
  expect(hasOtherAuthor('Add mean\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)')).toBe(true)
  expect(hasOtherAuthor('Add mean\n\nGenerated by GitHub Copilot')).toBe(true)
  expect(hasOtherAuthor('Add mean\n\nThe code generated by the parser is cached.')).toBe(false)

  const patch = [
    'diff --git a/stats.py b/stats.py',
    '--- a/stats.py',
    '+++ b/stats.py',
    '@@ -0,0 +1,2 @@',
    '+def mean(xs):',
    '+    return sum(xs) / len(xs)',
    'diff --git a/package-lock.json b/package-lock.json',
    '+++ b/package-lock.json',
    '+{}',
    'diff --git a/README.md b/README.md',
    '+++ b/README.md',
    '+# Stats',
    'diff --git a/deploy.sh b/deploy.sh',
    '+++ b/deploy.sh',
    '+echo hi',
  ].join('\n')
  const files = addedLines(patch)
  // Lock files and files in no language are not judged.
  expect(files).toEqual([
    { path: 'stats.py', language: 'python', lines: ['def mean(xs):', '    return sum(xs) / len(xs)'] },
    { path: 'deploy.sh', language: 'shell', lines: ['echo hi'] },
  ])
  expect([...byLanguage(files).keys()]).toEqual(['python', 'shell'])

  const mine = { hash: 'abc1234', parents: ['p1'], email: 'me@example.com', name: 'Me', message: 'Add mean' }
  expect(judge(mine, ['me@example.com'], files).isYours).toBe(true)
  const refused = (verdict: ReturnType<typeof judge>): string => (verdict.isYours ? '' : verdict.reason)
  expect(refused(judge({ ...mine, email: 'guido@python.org', name: 'Guido' }, ['me@example.com'], files))).toBe('it was written by Guido <guido@python.org>')
  expect(refused(judge(mine, [], files))).toMatch('git has no user.email here')
  expect(refused(judge({ ...mine, parents: ['p1', 'p2'] }, ['me@example.com'], files))).toBe('it is a merge')
  expect(refused(judge({ ...mine, message: 'Add mean\n\nCo-Authored-By: Claude <noreply@anthropic.com>' }, ['me@example.com'], files))).toMatch('co-author')
  expect(refused(judge(mine, ['me@example.com'], []))).toBe('it adds no source code')
  const bulk = [{ path: 'vendor.py', language: 'python', lines: Array.from({ length: MAX_ADDED_LINES + 1 }, (_, index) => `x${index} = ${index}`) }]
  expect(refused(judge(mine, ['me@example.com'], bulk))).toMatch('reads as an import or generated code')
})

test('no level until five observations from two commits, and a first placement never outruns the evidence', async () => {
  const four = [seen('a', 'naming', 'shown', 'junior'), seen('a', 'loops', 'shown', 'junior'), seen('b', 'tests', 'shown', 'junior'), seen('b', 'errors', 'missed', 'junior')]
  expect(decideLevel(record(four), 'junior').level).toBe(null)
  // Five, but all from one commit.
  expect(decideLevel(record([...four.slice(0, 2), seen('a', 'x', 'shown', 'junior'), seen('a', 'y', 'shown', 'junior'), seen('a', 'z', 'shown', 'junior')]), 'junior').level).toBe(null)

  const five = [...four, seen('b', 'idioms', 'shown', 'junior')]
  const placed = decideLevel(record(five), 'junior')
  expect(placed.level).toBe('junior')
  expect(placed.isProvisional).toBe(true)
  expect(placed.reason).toBe('First placement, from 5 observations over 2 commits.')

  // The model says senior. The evidence supports junior, and junior it is.
  expect(decideLevel(record(five), 'senior').level).toBe('junior')
  // The model is more cautious than the evidence: its reading stands.
  expect(decideLevel(record(five), 'beginner').level).toBe('beginner')
})

test('a step up takes new evidence at the next level from two commits, and the model agreeing', async () => {
  const placed = { at: 1, from: null, to: 'junior' as const, reason: 'First placement.', observationCount: 5 }
  const base = Array.from({ length: 5 }, (_, index) => seen(`c${index % 2}`, `s${index}`, 'shown', 'junior'))
  const ahead = [seen('d', 'interfaces', 'shown', 'mid'), seen('d', 'tests', 'shown', 'mid'), seen('e', 'errors', 'shown', 'mid'), seen('e', 'design', 'shown', 'mid')]
  const atJunior = (observations: Observation[]): ProgressRecord => record([...base, ...observations], 'junior', { history: [placed] })

  expect(decideLevel(atJunior(ahead), 'mid').level).toBe('mid')
  // One step at a time, whatever the model says.
  expect(decideLevel(atJunior(ahead), 'senior').level).toBe('mid')
  // The model does not see it yet: no move.
  expect(decideLevel(atJunior(ahead), 'junior').level).toBe('junior')
  // The same evidence from one commit is one good afternoon, not a level.
  expect(decideLevel(atJunior(ahead.map(item => ({ ...item, commit: 'd' }))), 'mid').level).toBe('junior')
  // Work the tutor did not watch arrive counts half, so it takes twice as much.
  expect(decideLevel(atJunior(ahead.map(item => ({ ...item, weight: 0.5 }))), 'mid').level).toBe('junior')
})

test('a level comes back down when what it assumes is missed, and the skill is marked slipping', async () => {
  const placed = { at: 1, from: null, to: 'mid' as const, reason: 'Placed.', observationCount: 6 }
  const base = [...Array.from({ length: 5 }, (_, index) => seen(`c${index % 2}`, `s${index}`, 'shown', 'mid')), seen('c0', 'edge-cases', 'shown', 'junior')]
  const missed = [seen('f', 'edge-cases', 'missed', 'junior'), seen('g', 'error-handling', 'missed', 'mid')]
  const atMid = record([...base, ...missed], 'mid', { history: [placed], isProvisional: false })

  const decided = decideLevel(atMid, 'mid')
  // Missed outweighs what was shown at this level since: down a step, even though the model held its ground.
  expect(decided.level).toBe('junior')
  expect(decided.reason).toBe('Down a step: 2 recent observations show mid work not yet solid (edge-cases, error-handling).')
  expect(skillStates(atMid).slipping).toEqual(['edge-cases'])
  expect(skillStates(atMid).working).toEqual(['error-handling'])

  // One bad commit alone does not.
  expect(decideLevel(record([...base, ...missed.map(item => ({ ...item, commit: 'f' }))], 'mid', { history: [placed] }), 'junior').level).toBe('mid')
})

test('withAssessment records what was seen once per commit, and keeps the history of every change', async () => {
  const first = withAssessment(emptyRecord('python'), SAW, [{ hash: 'a'.repeat(40), short: 'aaaaaaa', weight: 1 }], 'stats', 10)
  expect(first.record.observations.map(item => `${item.commit.slice(0, 7)} ${item.verdict} ${item.skill} x${item.weight}`)).toEqual(['aaaaaaa missed edge-cases x1', 'aaaaaaa shown naming x1'])
  expect(first.record.report?.why).toBe('Small, working functions with clear names.')
  expect(first.change).toBe(null)
  expect(levelPhrase(first.record)).toBe('no level yet: 2 of 5 observations, from 1 of 2 commits')

  // The same commit again, from another project or another session, adds nothing.
  expect(withAssessment(first.record, SAW, [{ hash: 'a'.repeat(40), short: 'aaaaaaa', weight: 1 }], 'fork', 20).record).toBe(first.record)

  const more: Assessment = { ...SAW, observations: [...SAW.observations, { ...SAW.observations[1]!, skill: 'idioms' }, { ...SAW.observations[1]!, skill: 'tests' }] }
  const second = withAssessment(first.record, more, [{ hash: 'b'.repeat(40), short: 'bbbbbbb', weight: 0.5 }], 'stats', 30)
  expect(second.record.level).toBe('junior')
  expect(second.change).toEqual({ at: 30, from: null, to: 'junior', reason: 'First placement, from 6 observations over 2 commits.', observationCount: 6 })
  expect(second.record.history).toEqual([second.change!])
  expect(parseRecord(JSON.parse(JSON.stringify(second.record)), 'python')).toEqual(second.record)
  expect(parseRecord({ ...second.record, language: 'rust' }, 'python')).toEqual(emptyRecord('python'))

  expect(recordText(second.record)).toMatch('Python: junior (provisional)\nWhy: Small, working functions with clear names.\nFor the next level: Handle the empty input on purpose, and test it.')
  expect(progressText([second.record])).toMatch('- Python: observed level junior (provisional).')
  expect(progressText([first.record])).toBe('')
})

test('parseAssessment takes what fits and drops the rest', async () => {
  expect(parseAssessment('no json')).toBe(null)
  const parsed = parseAssessment(
    'Here:\n{"observations": [{"skill": "Edge Cases!", "verdict": "missed", "level": "junior", "note": "x"}, {"skill": "a", "verdict": "great", "level": "junior", "note": "x"}, {"skill": "b", "verdict": "shown", "level": "wizard", "note": "x"}], "level": "guru", "why": "w", "working": ["one", 2]}',
  )
  expect(parsed?.observations).toEqual([{ commit: '', skill: 'edge-cases', verdict: 'missed', level: 'junior', note: 'x' }])
  expect(parsed?.level).toBe(null)
  expect(parsed?.working).toEqual(['one'])
})

test('the request shows only their added lines, and says that what they said about themselves is not evidence', async () => {
  const request = assessmentRequest({
    language: 'python',
    project: 'stats',
    record: emptyRecord('python'),
    said: 'Has written: For years',
    commits: [{ short: 'abc1234', title: 'Add mean', files: [{ path: 'stats.py', lines: ['def mean(xs):', '    return sum(xs) / len(xs)'] }] }],
    review: 'Nice.',
  })
  expect(request).toMatch('Language: Python. Project: stats.')
  expect(request).toMatch('It is not evidence, and it does not move the level: Has written: For years')
  expect(request).toMatch('### Commit abc1234: Add mean\n--- stats.py\n+def mean(xs):\n+    return sum(xs) / len(xs)')
  expect(request).toMatch('The deep review of this commit, for context. Judge the lines yourself:\nNice.')
})

const OBSERVED = (commit: string): Assessment => ({
  observations: ['naming', 'idioms', 'edge-cases'].map(skill => ({ commit, skill, verdict: 'shown' as const, level: 'junior' as const, note: `stats.py: ${skill}.` })),
  level: 'junior',
  why: 'Clear, small functions.',
  next: 'Design a module with a clear interface.',
  working: ['testing'],
  encouragement: 'Steady work.',
})

sessionTest('your commit is assessed after its review, on your own lines, and two of them place you', async ($, on) => {
  const session = stubSession(on, { head: { 'stats.py': MEAN } })
  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()
  // The one commit there was is too small to place anyone.
  expect(session.assessments.length).toBe(0)

  session.write('stats.py', `${MEAN}\n\ndef total(xs):\n    result = sum(xs)\n    return result\n`)
  await session.clock.advance(4000)
  const first = session.commit('Add total')
  await session.clock.advance(2000)
  session.assess(OBSERVED(''))
  await $.turn.complete(session.finish(1, 'Good, small change.'))
  await session.clock.settle()

  const request = session.assessments[0]
  expect(request?.model).toBe('opus')
  expect(request?.effort).toBe('high')
  expect(request?.prompt).toMatch(`### Commit ${first.slice(0, 7)}: Add total\n--- stats.py\n+def total(xs):\n+    result = sum(xs)\n+    return result`)
  // The code that was already there is someone's, maybe theirs, but not part of this commit: it is not shown.
  expect(request?.prompt.includes('def mean(xs):')).toBe(false)
  expect(request?.prompt).toMatch('The deep review of this commit, for context. Judge the lines yourself:\nGood, small change.')
  const stored = parseRecord(session.data('progress/python.json'), 'python')
  // The watcher saw stats.py change before the commit, so what was seen counts in full.
  expect(stored.observations.map(item => item.weight)).toEqual([1, 1, 1])

  session.write('stats.py', `${MEAN}\n\ndef total(xs):\n    result = sum(xs)\n    return result\n\ndef count(xs):\n    n = len(xs)\n    return n\n`)
  await session.clock.advance(4000)
  const second = session.commit('Add count')
  await session.clock.advance(2000)
  session.assess(OBSERVED(second.slice(0, 7)))
  await $.turn.complete(session.finish(2, 'Fine.'))
  await session.clock.settle()

  expect(parseRecord(session.data('progress/python.json'), 'python').level).toBe('junior')
  expect(session.toasts).toContain('Python: junior (provisional). See the Progress tab.')

  const ui = await $.ui.mount({ ...PANE, surface: 'terminal' })
  await ui.press({ key: 'tab-profile' })
  expect(await ui.find({ type: 'Text', text: 'Level: junior (provisional)' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: 'Next level: Design a module with a clear interface.' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: 'Steady work.' })).toBeDefined()
  expect(await ui.find({ type: 'Text', text: `- Showed edge cases in work (${second.slice(0, 7)}): stats.py: edge-cases.` })).toBeDefined()
  await ui.unmount()

  // The tutor, both reviewers and the tool all know it now.
  const { sections } = await $.prompt.compose(COMPOSE)
  expect(sections[sections.length - 1]?.text).toMatch('- Python: observed level junior (provisional).')
  expect(session.agents[session.agents.length - 1]?.prompt).toMatch('- Python: observed level junior (provisional).')
  const told = String(((await $.tool.call({ tool: 'mcp__backseat-driver__progress', language: 'python' })) as { result: unknown }).result)
  expect(told).toMatch('Python: junior (provisional)')
  expect(told).toMatch('Only commits by me@example.com count.')
})

sessionTest("someone else's commit, a co-authored one and a bulk import are not yours, and the tab says why", async ($, on) => {
  const session = stubSession(on, { head: { 'stats.py': MEAN } })
  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()
  const before = session.assessments.length

  session.write('stats.py', `${MEAN}\n\ndef total(xs):\n    result = sum(xs)\n    return result\n`)
  const theirs = session.commit('Add total', { author: { name: 'Guido', email: 'guido@python.org' } })
  await session.clock.advance(2000)
  await $.turn.complete(session.finish(1, 'Fine.'))
  await session.clock.settle()

  const ui = await $.ui.mount({ ...PANE, surface: 'terminal' })
  await ui.press({ key: 'tab-profile' })
  expect(await ui.find({ type: 'Text', text: `Commit ${theirs.slice(0, 7)} does not count toward your progress: it was written by Guido <guido@python.org>.` })).toBeDefined()
  await ui.unmount()

  session.write('stats.py', `${MEAN}\n\ndef count(xs):\n    n = len(xs)\n    return n\n`)
  session.commit('Add count', { body: 'Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>' })
  await session.clock.advance(2000)
  await $.turn.complete(session.finish(2, 'Fine.'))
  await session.clock.settle()

  session.write('vendor.py', Array.from({ length: 700 }, (_, index) => `x${index} = ${index}`).join('\n'))
  session.commit('Vendor a library')
  await session.clock.advance(2000)
  await $.turn.complete(session.finish(3, 'Fine.'))
  await session.clock.settle()

  expect(session.assessments.length).toBe(before)
  expect(session.data('progress/python.json')).toBeUndefined()
})

sessionTest('a commit of yours too small to say anything is not assessed, and the tab says so', async ($, on) => {
  const session = stubSession(on, { head: { 'stats.py': MEAN } })
  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()

  session.write('stats.py', `${MEAN}\n# A comment.\n`)
  const small = session.commit('Add a comment')
  await session.clock.advance(2000)
  await $.turn.complete(session.finish(1, 'Fine.'))
  await session.clock.settle()

  expect(session.assessments).toEqual([])
  const ui = await $.ui.mount({ ...PANE, surface: 'terminal' })
  await ui.press({ key: 'tab-profile' })
  expect(await ui.find({ type: 'Text', text: `Commit ${small.slice(0, 7)} is too small to say anything about your progress.` })).toBeDefined()
  await ui.unmount()
})

sessionTest('a first placement reads only your commits, however much better the rest of the history is', async ($, on) => {
  const session = stubSession(on, { head: { 'README.txt': 'A famous library.\n' } })
  // A well-known project: years of excellent work by its maintainers...
  for (let index = 0; index < 4; index += 1) {
    session.write(`core${index}.py`, `class Engine${index}:\n    """Battle-tested."""\n\n    def run(self):\n        return ${index}\n`)
    session.commit(`Core ${index}`, { author: { name: 'Maintainer', email: 'maintainer@famous.org' } })
  }
  // ...and one small commit of yours.
  session.write('core0.py', `class Engine0:\n    """Battle-tested."""\n\n    def run(self):\n        return 0\n\n    def stop(self):\n        """Stop the engine."""\n        print("stop")\n`)
  const mine = session.commit('Add stop')
  session.assess({ ...OBSERVED(mine.slice(0, 7)), level: 'beginner' })

  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()

  expect(session.assessments.length).toBe(1)
  const request = session.assessments[0]?.prompt ?? ''
  expect(request).toMatch(`### Commit ${mine.slice(0, 7)}: Add stop\n--- core0.py\n+    def stop(self):\n+        """Stop the engine."""\n+        print("stop")`)
  expect(request.includes('Battle-tested')).toBe(false)
  expect(request.includes('Core 1')).toBe(false)
  // Work the tutor did not watch counts half.
  expect(parseRecord(session.data('progress/python.json'), 'python').observations.every(item => item.weight === 0.5)).toBe(true)
})

sessionTest('with deep reviews off after commits, a commit of yours is still assessed when it is made', { options: { deep_review_after_commit: false } }, async ($, on) => {
  const session = stubSession(on, { head: { 'stats.py': MEAN } })
  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()
  const before = session.assessments.length

  session.write('stats.py', `${MEAN}\n\ndef total(xs):\n    result = sum(xs)\n    return result\n`)
  await session.clock.advance(4000)
  session.commit('Add total')
  await session.clock.advance(2000)
  await session.clock.settle()

  expect(session.spawned).toEqual([])
  expect(session.assessments.length).toBe(before + 1)
  expect(session.assessments[before]?.prompt.includes('The deep review of this commit')).toBe(false)
})

sessionTest('with the report off, nothing is assessed and the tab says so', { options: { progress_report: false } }, async ($, on) => {
  const session = stubSession(on, { head: { 'stats.py': MEAN } })
  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()
  session.write('stats.py', `${MEAN}\n\ndef total(xs):\n    result = sum(xs)\n    return result\n`)
  await session.clock.advance(4000)
  session.commit('Add total')
  await session.clock.advance(2000)
  await $.turn.complete(session.finish(1, 'Fine.'))
  await session.clock.settle()

  expect(session.assessments).toEqual([])
  const ui = await $.ui.mount({ ...PANE, surface: 'terminal' })
  await ui.press({ key: 'tab-profile' })
  expect(await ui.find({ type: 'Text', text: 'The progress report is switched off. Its setting is in /config.' })).toBeDefined()
  await ui.unmount()
})

sessionTest('with no email in git, nothing can be confirmed as yours', { options: {} }, async ($, on) => {
  const session = stubSession(on, { head: { 'stats.py': MEAN }, email: '' })
  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()

  expect(session.assessments).toEqual([])
  const ui = await $.ui.mount({ ...PANE, surface: 'terminal' })
  await ui.press({ key: 'tab-profile' })
  expect(await ui.find({ type: 'Text', text: 'Git has no user.email here, so no commit can be confirmed as yours and nothing is scored.' })).toBeDefined()
  await ui.unmount()
})

sessionTest('forgetting a language forgets its progress too', async ($, on) => {
  const placed = withAssessment(emptyRecord('python'), OBSERVED('aaaaaaa'), [{ hash: 'a'.repeat(40), short: 'aaaaaaa', weight: 1 }], 'stats', 1).record
  const session = stubSession(on, { head: { 'stats.py': MEAN }, data: { 'progress/python.json': placed } })
  session.disk.set(`${DATA_HOME}/.backseat-driver`, 'marker')
  await $.session.start(SESSION)
  await $.command.run(typed('bsd'))
  await session.clock.settle()

  session.answers.push(FORGET)
  await $.command.run(typed('bsd', 'forget python'))
  await session.clock.settle()
  expect(session.data('progress/python.json')).toBeUndefined()
  const told = String(((await $.tool.call({ tool: 'mcp__backseat-driver__progress', language: 'python' })) as { result: unknown }).result)
  expect(told).toMatch('Nothing is on record for python yet.')
})

test('showing and missing a skill in the same commit is a mixed result, not a slip', async () => {
  const mixed = record([seen('a', 'edge-cases', 'shown', 'junior'), seen('a', 'edge-cases', 'missed', 'mid')])
  expect(skillStates(mixed)).toEqual({ shown: ['edge-cases'], slipping: [], working: [] })

  const slipped = record([...mixed.observations, seen('b', 'edge-cases', 'missed', 'junior')])
  expect(skillStates(slipped)).toEqual({ shown: [], slipping: ['edge-cases'], working: [] })

  const recovered = record([...slipped.observations, seen('c', 'edge-cases', 'shown', 'junior')])
  expect(skillStates(recovered).shown).toEqual(['edge-cases'])
  expect(skillStates(record([seen('a', 'testing', 'missed', 'junior'), seen('b', 'testing', 'missed', 'junior')])).working).toEqual(['testing'])
})

test('observations from several commits are kept oldest commit first, whatever order the model gave them', async () => {
  const older = { hash: 'a'.repeat(40), short: 'aaaaaaa', weight: 0.5 }
  const newer = { hash: 'b'.repeat(40), short: 'bbbbbbb', weight: 0.5 }
  const assessment: Assessment = {
    ...SAW,
    observations: [
      { commit: 'bbbbbbb', skill: 'edge-cases', verdict: 'shown', level: 'junior', note: 'perimeter rejects negative sizes.' },
      { commit: 'aaaaaaa', skill: 'edge-cases', verdict: 'missed', level: 'junior', note: 'area accepts anything.' },
    ],
  }
  const { record: kept } = withAssessment(emptyRecord('python'), assessment, [older, newer], 'shapes', 1)
  expect(kept.observations.map(item => item.commit.slice(0, 7))).toEqual(['aaaaaaa', 'bbbbbbb'])
  // Missed first, shown later: improving, not slipping.
  expect(skillStates(kept)).toEqual({ shown: ['edge-cases'], slipping: [], working: [] })
})
